import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Smartphone, QrCode, ExternalLink, Copy, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

interface InnBucksPaymentProps {
    amount: number;
    onSuccess: (paymentData: any) => void;
    onCancel: () => void;
    loading?: boolean;
}

export default function InnBucksPayment({ amount, onSuccess, onCancel, loading }: InnBucksPaymentProps) {
    const [authorizationCode, setAuthorizationCode] = useState('');
    const [paymentInitiated, setPaymentInitiated] = useState(false);
    const [processing, setProcessing] = useState(false);
    const [copied, setCopied] = useState(false);
    const [errors, setErrors] = useState<Record<string, string>>({});

    // Generate authorization code when payment is initiated
    useEffect(() => {
        if (paymentInitiated && !authorizationCode) {
            // In production, this would be generated by backend
            const code = `INN-${Date.now().toString().slice(-8)}`;
            setAuthorizationCode(code);
        }
    }, [paymentInitiated, authorizationCode]);

    const handleInitiatePayment = () => {
        setPaymentInitiated(true);
    };

    const handleCopyCode = async () => {
        try {
            await navigator.clipboard.writeText(authorizationCode);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error('Failed to copy code:', error);
        }
    };

    const handleOpenApp = () => {
        // Deep link to InnBucks app with prefilled code
        const deepLink = `innbucks://pay?code=${authorizationCode}&amount=${amount}`;
        window.location.href = deepLink;

        // Fallback to app store if app is not installed
        setTimeout(() => {
            window.open('https://play.google.com/store/apps/details?id=zw.co.innbucks', '_blank');
        }, 2000);
    };

    const handleConfirmPayment = async () => {
        setProcessing(true);
        try {
            const paymentData = {
                method: 'innbucks',
                amount,
                currency: 'USD', // InnBucks is USD only
                authorizationCode,
                paymentStatus: 'pending',
                transactionId: `INNBUCKS-${Date.now()}`,
            };

            onSuccess(paymentData);
        } catch (error) {
            setErrors({ submit: 'Payment confirmation failed. Please try again.' });
        } finally {
            setProcessing(false);
        }
    };

    return (
        <div className="space-y-4">
            <div className="bg-orange-50 dark:bg-orange-950/20 border border-orange-200 dark:border-orange-800 rounded-lg p-4">
                <div className="flex items-start gap-3">
                    <Smartphone className="h-5 w-5 text-orange-600 flex-shrink-0 mt-0.5" />
                    <div>
                        <h4 className="font-semibold text-sm text-orange-900 dark:text-orange-100 mb-1">
                            InnBucks Payment (USD Only)
                        </h4>
                        <p className="text-sm text-orange-700 dark:text-orange-300">
                            Complete payment using the InnBucks mobile app via authorization code, QR scan, or deep link.
                        </p>
                    </div>
                </div>
            </div>

            {errors.submit && (
                <div className="bg-red-50 dark:bg-red-950/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                    <div className="flex items-start gap-3">
                        <AlertCircle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                        <p className="text-sm text-red-700 dark:text-red-300">{errors.submit}</p>
                    </div>
                </div>
            )}

            {!paymentInitiated ? (
                <>
                    <div className="bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                        <h4 className="font-semibold text-sm text-blue-900 dark:text-blue-100 mb-2">
                            Payment Amount
                        </h4>
                        <p className="text-2xl font-bold text-blue-700 dark:text-blue-300">
                            USD ${amount.toFixed(2)}
                        </p>
                    </div>

                    <div className="space-y-2 text-sm text-[#706f6c] dark:text-[#A1A09A]">
                        <p className="font-semibold text-[#1b1b18] dark:text-[#EDEDEC]">
                            Three ways to complete payment:
                        </p>
                        <ol className="space-y-1 ml-4">
                            <li className="list-decimal">Enter authorization code manually in InnBucks app</li>
                            <li className="list-decimal">Scan QR code with InnBucks app</li>
                            <li className="list-decimal">Use deep link to open app with code prefilled</li>
                        </ol>
                    </div>

                    <div className="flex gap-3 pt-4">
                        <Button
                            onClick={onCancel}
                            variant="outline"
                            className="flex-1"
                            disabled={processing || loading}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleInitiatePayment}
                            className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                            disabled={processing || loading}
                        >
                            <Smartphone className="mr-2 h-5 w-5" />
                            Generate Code
                        </Button>
                    </div>
                </>
            ) : (
                <>
                    {/* Authorization Code Display */}
                    <div className="bg-gradient-to-br from-emerald-50 to-blue-50 dark:from-emerald-950/20 dark:to-blue-950/20 border-2 border-emerald-200 dark:border-emerald-800 rounded-lg p-6">
                        <div className="text-center space-y-3">
                            <h4 className="font-semibold text-sm text-[#1b1b18] dark:text-[#EDEDEC]">
                                Your Authorization Code
                            </h4>
                            <div className="bg-white dark:bg-gray-800 rounded-lg p-4 border-2 border-dashed border-emerald-300 dark:border-emerald-700">
                                <p className="text-3xl font-mono font-bold text-emerald-600 tracking-wider">
                                    {authorizationCode}
                                </p>
                            </div>
                            <Button
                                onClick={handleCopyCode}
                                variant="outline"
                                size="sm"
                                className="w-full"
                            >
                                {copied ? (
                                    <>
                                        <CheckCircle className="mr-2 h-4 w-4 text-green-600" />
                                        Copied!
                                    </>
                                ) : (
                                    <>
                                        <Copy className="mr-2 h-4 w-4" />
                                        Copy Code
                                    </>
                                )}
                            </Button>
                        </div>
                    </div>

                    {/* Payment Methods */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                        {/* Method 1: Manual Entry */}
                        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                            <div className="flex flex-col items-center text-center space-y-2">
                                <Smartphone className="h-8 w-8 text-emerald-600" />
                                <h5 className="font-semibold text-sm text-[#1b1b18] dark:text-[#EDEDEC]">
                                    Manual Entry
                                </h5>
                                <p className="text-xs text-[#706f6c] dark:text-[#A1A09A]">
                                    Open InnBucks app and enter the code manually
                                </p>
                            </div>
                        </div>

                        {/* Method 2: QR Code */}
                        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                            <div className="flex flex-col items-center text-center space-y-2">
                                <QrCode className="h-8 w-8 text-emerald-600" />
                                <h5 className="font-semibold text-sm text-[#1b1b18] dark:text-[#EDEDEC]">
                                    QR Code
                                </h5>
                                <p className="text-xs text-[#706f6c] dark:text-[#A1A09A]">
                                    Scan with InnBucks app camera
                                </p>
                                {/* In production, generate actual QR code here */}
                                <div className="w-24 h-24 bg-gray-200 dark:bg-gray-700 rounded flex items-center justify-center">
                                    <QrCode className="h-12 w-12 text-gray-400" />
                                </div>
                            </div>
                        </div>

                        {/* Method 3: Deep Link */}
                        <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                            <div className="flex flex-col items-center text-center space-y-2">
                                <ExternalLink className="h-8 w-8 text-emerald-600" />
                                <h5 className="font-semibold text-sm text-[#1b1b18] dark:text-[#EDEDEC]">
                                    Open App
                                </h5>
                                <p className="text-xs text-[#706f6c] dark:text-[#A1A09A] mb-2">
                                    Launch app with code prefilled
                                </p>
                                <Button
                                    onClick={handleOpenApp}
                                    size="sm"
                                    variant="outline"
                                    className="w-full"
                                >
                                    <ExternalLink className="mr-2 h-4 w-4" />
                                    Open InnBucks
                                </Button>
                            </div>
                        </div>
                    </div>

                    {/* Instructions */}
                    <div className="bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                        <h4 className="font-semibold text-sm text-blue-900 dark:text-blue-100 mb-2">
                            Complete Payment in InnBucks App:
                        </h4>
                        <ol className="text-sm text-blue-700 dark:text-blue-300 space-y-1 ml-4">
                            <li className="list-decimal">Use any method above to enter the code</li>
                            <li className="list-decimal">Verify amount: <strong>USD ${amount.toFixed(2)}</strong></li>
                            <li className="list-decimal">Enter your InnBucks PIN</li>
                            <li className="list-decimal">Confirm the transaction</li>
                            <li className="list-decimal">Click "I've Authorized Payment" below</li>
                        </ol>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex gap-3 pt-4">
                        <Button
                            onClick={() => setPaymentInitiated(false)}
                            variant="outline"
                            className="flex-1"
                            disabled={processing || loading}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleConfirmPayment}
                            className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                            disabled={processing || loading}
                        >
                            {processing || loading ? (
                                <>
                                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                    Confirming...
                                </>
                            ) : (
                                <>
                                    <CheckCircle className="mr-2 h-5 w-5" />
                                    I've Authorized Payment
                                </>
                            )}
                        </Button>
                    </div>
                </>
            )}

            <p className="text-xs text-center text-[#706f6c] dark:text-[#A1A09A]">
                USD only • Funds settle to merchant USD account
            </p>
        </div>
    );
}
